/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PMGButton: typeof import('./src/components/button/PMGButton.vue')['default']
    PMGInput: typeof import('./src/components/form/PMGInput.vue')['default']
  }
}
